[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "open-bos-stream"
description = "Open Source BOS Video Streaming Server"
requires-python = ">=3.13"
dynamic = ["version"]

dependencies = [
    "fastapi",
    "uvicorn",
    "jinja2",
    "pyyaml",
    "psutil",
    "pillow"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.dynamic]
version = {attr = "open_bos_stream.version.VERSION"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
open_bos_stream = [
    "map/styles/*.json",
    "map/layers/*.geojson",
    "map/glyphs/*/*.pbf",
    "static/css/*.css",
    "static/js/*.js",
    "static/vendor/*.js",
    "static/vendor/*.css",
    "static/vendor/mediamtx/*.js",
    "static/vendor/maplibre/*.js",
    "static/vendor/maplibre/*.css",
    "templates/*.html",
    "templates/components/*.html",
    "templates/components/video/*.html",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
